import { ITopXBottom, IXY } from './TTopRightBottomLeft'

export const FONT_FAMILY_NORMAL = '"Segoe UI", Tahoma, sans-serif'
export const FONT_SIZE_H000 = 80
export const FONT_SIZE_H00 = 60
export const FONT_SIZE_H0 = 48
export const FONT_SIZE_H1 = 32
export const FONT_SIZE_H2 = 28
export const FONT_SIZE_H3 = 24
export const FONT_SIZE_H4 = 20
export const FONT_SIZE_H5 = 18
export const FONT_SIZE_H6 = 16
export const FONT_SIZE_NORMAL = 14
export const FONT_SIZE_SMALL = 12
export const FONT_SIZE_TINY = 10
export const LINE_HEIGHT_H000 = `91px`
export const LINE_HEIGHT_H00 = `69px`
export const LINE_HEIGHT_H0 = `55px`
export const LINE_HEIGHT_H1 = `37px`
export const LINE_HEIGHT_H2 = `32px`
export const LINE_HEIGHT_H3 = `27px`
export const LINE_HEIGHT_H4 = `23px`
export const LINE_HEIGHT_H5 = `21px`
export const LINE_HEIGHT_H6 = `18px`
export const LINE_HEIGHT_NORMAL = `16px`
export const LINE_HEIGHT_SMALL = `14px`
export const LINE_HEIGHT_TINY = `11px`
export const TRANSPARENT = 'transparent'
export const WHITE = '#fff'
export const BLACK = '#000'
export const BLACK_1 = 'rgba(0, 0, 0, .05)'
export const BLACK_2 = 'rgba(0, 0, 0, .1)'
export const BLACK_3 = 'rgba(0, 0, 0, .2)'
export const BLACK_4 = 'rgba(0, 0, 0, .4)'
export const BLACK_5 = 'rgba(0, 0, 0, .6)'
export const BLACK_6 = 'rgba(0, 0, 0, .8)'
export const BLACK_7 = 'rgba(0, 0, 0, .9)'
export const GRAY_1 = '#fafafa'
export const GRAY_2 = '#f0f0f0'
export const GRAY_3 = '#d6d6d6'
export const GRAY_4 = '#a6a6a6'
export const GRAY_5 = '#7e7e7e'
export const GRAY_6 = '#545454'
export const GRAY_7 = '#2b2b2b'
export const TEAL_1 = '#e3faff'
export const TEAL_2 = '#afe8f4'
export const TEAL_3 = '#7cccdb'
export const TEAL_4 = '#4998AA'
export const TEAL_5 = '#206570'
export const TEAL_6 = '#0e3e46'
export const TEAL_7 = '#052025'
export const ORANGE_1 = '#FFF5EC'
export const ORANGE_2 = '#FFEBD7'
export const ORANGE_3 = '#FFC68D'
export const ORANGE_4 = '#FFA836'
export const ORANGE_5 = '#EA6A00'
export const ORANGE_6 = '#AF2500'
export const ORANGE_7 = '#680A00'
export const BLUE_1 = '#E4F9FF'
export const BLUE_2 = '#C0F2FF'
export const BLUE_3 = '#9be1ff'
export const BLUE_4 = '#68aee0'
export const BLUE_5 = '#0084CE'
export const BLUE_6 = '#00478E'
export const BLUE_7 = '#00264C'
export const RED_1 = '#FFDEDE'
export const RED_2 = '#FFC5C5'
export const RED_3 = '#F98A8A'
export const RED_4 = '#E53838'
export const RED_5 = '#BF0000'
export const RED_6 = '#890014'
export const RED_7 = '#540018'
export const GREEN_1 = '#F5FCEB'
export const GREEN_2 = '#E5F2D1'
export const GREEN_3 = '#C1E58F'
export const GREEN_4 = '#92d050'
export const GREEN_5 = '#6CA028'
export const GREEN_6 = '#4C7014'
export const GREEN_7 = '#33490D'
export const PADDING_NO_X: Readonly<IXY> = { x: 0, y: 1 }
export const PADDING_SHORT: Readonly<IXY> = { x: .5, y: 1 }
export const LIGHT = 300
export const NORMAL = 400
export const SEMIBOLD = 600
export const BOLD = 700
export const RADIUS = '3px'
export const BUTTON_PADDING_TOP = 2
export const BUTTON_PADDING_BOTTOM = 4
export const BUTTON_PADDING_X = 5
export const BUTTON_PADDING: Readonly<ITopXBottom> = { t: BUTTON_PADDING_TOP, x: BUTTON_PADDING_X, b: BUTTON_PADDING_BOTTOM }
export const DURATION = '.25s'
export const SHADOW = `0 1px 3px ${BLACK_2}`
export const WINDOW_SHADOW = `0 5px 20px ${BLACK_6}`
export const BORDER = `1px solid ${BLACK_3}`
export const BORDER_SHADOW = `inset 0 0 0 1px ${BLACK_3}`
